#Dataframes
1. Columnas (Features - características)
2. Filas (registros)

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
#Convertir de lista a dataframe
ventas=pd.Series([22,15,70])
ventas

0    22
1    15
2    70
dtype: int64

In [ ]:
ventas=pd.Series([22,15,70],index=["Enero","Febrero","Marzo"])
ventas

Enero      22
Febrero    15
Marzo      70
dtype: int64

In [ ]:
ventas[0]

<ipython-input-4-eacc5df2ea8a>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  ventas[0]


22

In [ ]:
ventas["Enero"]

22

In [ ]:
ventas.dtype

dtype('int64')

In [ ]:
#Para visualización de features
ventas.index

Index(['Enero', 'Febrero', 'Marzo'], dtype='object')

In [ ]:
#Para obtener los valores de la feature
ventas.values

array([22, 15, 70])

In [ ]:
ventas.name="Ventas 2025"
ventas

Enero      22
Febrero    15
Marzo      70
Name: Ventas 2025, dtype: int64

In [ ]:
ventas.index.name="Meses"
ventas

Meses
Enero      22
Febrero    15
Marzo      70
Name: Ventas 2025, dtype: int64

In [ ]:
ventas.shape

(3,)

##Conversión de diccionario a dataframe

###Diccionarios
1. No tienen indexación
2. Poseen una clave única, y un valor asociado a la clave.
3. Son mutables

In [ ]:
diccionario={"Enero":22,"Febrero":15,"Marzo":70}
type(diccionario)

dict

In [ ]:
ventas1=pd.Series(diccionario)
ventas1

Enero      22
Febrero    15
Marzo      70
dtype: int64

In [ ]:
alex=pd.Series(diccionario,index=["Enero","Febrero","Marzo","Abril"])
alex

Enero      22.0
Febrero    15.0
Marzo      70.0
Abril       NaN
dtype: float64

In [ ]:
medidas=pd.DataFrame(
    {"Humedad":[41,20,30,80],
     "Salinidad":[22,15,30,80],
     "Sensórica":["sí","no","no","no"],
     "Acidez":["alta","media","baja","baja"],
     "Ph":[1,7,14,13]},
    index=["La Ureña","Paso Chico","La Laguna","Los Teres"]
    )
medidas

Humedad  Salinidad Sensórica Acidez  Ph
La Ureña         41         22        sí   alta   1
Paso Chico       20         15        no  media   7
La Laguna        30         30        no   baja  14
Los Teres        80         80        no   baja  13

In [ ]:
medidas.index.name="Veredas"
medidas

Humedad  Salinidad Sensórica Acidez  Ph
Veredas                                            
La Ureña         41         22        sí   alta   1
Paso Chico       20         15        no  media   7
La Laguna        30         30        no   baja  14
Los Teres        80         80        no   baja  13

In [ ]:
medidas.Humedad

Veredas
La Ureña      41
Paso Chico    20
La Laguna     30
Los Teres     80
Name: Humedad, dtype: int64

In [ ]:
medidas.columns

Index(['Humedad', 'Salinidad', 'Sensórica', 'Acidez', 'Ph'], dtype='object')

In [ ]:
medidas[["Ph","Acidez"]]

Ph Acidez
Veredas              
La Ureña     1   alta
Paso Chico   7  media
La Laguna   14   baja
Los Teres   13   baja

In [ ]:
medidas.dtypes

Humedad       int64
Salinidad     int64
Sensórica    object
Acidez       object
Ph            int64
dtype: object

In [ ]:
#Muestra los nombre de filas y columnas
medidas.axes

[Index(['La Ureña', 'Paso Chico', 'La Laguna', 'Los Teres'], dtype='object', name='Veredas'),
 Index(['Humedad', 'Salinidad', 'Sensórica', 'Acidez', 'Ph'], dtype='object')]

In [ ]:
medidas.values

array([[41, 22, 'sí', 'alta', 1],
       [20, 15, 'no', 'media', 7],
       [30, 30, 'no', 'baja', 14],
       [80, 80, 'no', 'baja', 13]], dtype=object)

In [ ]:
medidas.shape

(4, 5)

###Ejercicios
Dados los siguientes diccionarios, convertirlos en datagramas y usar todos los métodos aprendidos:

```
elementos={"número atómico":[1,6,47,88],
"Masa atómica":[1,12,107,226],
"Familia":["No metal","No metal","Metal","Metal"]}
```
Agregar como registros el nombre de los elementos

2. Convertir en dataframe el siguiente conjunto de medidas
```
medida_2020={"Ag":2,"Au":5,"Cu":3,"Pt:2}
medida_2021={"Ag":4,"Au":3,"Cu":6,"Pt:1}
medida_2022={"Ag":8,"Au":2,"Cu":15,"Pt:0}
medida_2023={"Ag":5,"Au":1,"Cu":0,"Pt:5}
medida_2024={"Ag":7,"Au":0,"Cu":3,"Pt:2}
medida_20205={"Ag":9,"Au":1,"Cu":3,"Pt:5}
```
Tenga en cuenta que los registros son los meses de medida y las features deben ser los elementos





In [24]:
elementos={"número atómico":[1,6,47,88],
"Masa atómica":[1,12,107,226],
"Familia":["No metal","No metal","Metal","Metal"]}
elementos

{'número atómico': [1, 6, 47, 88],
 'Masa atómica': [1, 12, 107, 226],
 'Familia': ['No metal', 'No metal', 'Metal', 'Metal']}

In [26]:
elementos=pd.DataFrame(elementos,index=["Silicio","Cloro","Mercurio","Xenon"])
elementos

número atómico  Masa atómica   Familia
Silicio                1             1  No metal
Cloro                  6            12  No metal
Mercurio              47           107     Metal
Xenon                 88           226     Metal

In [28]:
elementos=elementos.rename(index={"Silicio":"Si","Cloro":"Cl","Mercurio":"Hg","Xenon":"Xe"})
elementos

número atómico  Masa atómica   Familia
Si               1             1  No metal
Cl               6            12  No metal
Hg              47           107     Metal
Xe              88           226     Metal

In [29]:
elementos=pd.DataFrame(elementos,index=["Si","Cl","Hg","Xe"])
elementos

número atómico  Masa atómica   Familia
Si               1             1  No metal
Cl               6            12  No metal
Hg              47           107     Metal
Xe              88           226     Metal

In [30]:
elementos.index.name="Simbolo"
elementos

número atómico  Masa atómica   Familia
Simbolo                                        
Si                    1             1  No metal
Cl                    6            12  No metal
Hg                   47           107     Metal
Xe                   88           226     Metal

In [31]:
elementos.values

array([[1, 1, 'No metal'],
       [6, 12, 'No metal'],
       [47, 107, 'Metal'],
       [88, 226, 'Metal']], dtype=object)

In [32]:
elementos.shape

(4, 3)

In [39]:
medida_2020 = {"Ag": 2, "Au": 5, "Cu": 3, "Pt": 2}
medida_2021 = {"Ag": 4, "Au": 3, "Cu": 6, "Pt": 1}
medida_2022 = {"Ag": 8, "Au": 2, "Cu": 15, "Pt": 0}
medida_2023 = {"Ag": 5, "Au": 1, "Cu": 0, "Pt": 5}
medida_2024 = {"Ag": 7, "Au": 0, "Cu": 3, "Pt": 2}
medida_2025 = {"Ag": 9, "Au": 1, "Cu": 3, "Pt": 5}

import pandas as pd

medidas_df = pd.DataFrame(
    {
        "2020": medida_2020,
        "2021": medida_2021,
        "2022": medida_2022,
        "2023": medida_2023,
        "2024": medida_2024,
        "2025": medida_2025,
    }
)

medidas_df


2020  2021  2022  2023  2024  2025
Ag     2     4     8     5     7     9
Au     5     3     2     1     0     1
Cu     3     6    15     0     3     3
Pt     2     1     0     5     2     5

In [40]:
medidas_df.dtypes

2020    int64
2021    int64
2022    int64
2023    int64
2024    int64
2025    int64
dtype: object

In [41]:
medidas_df.shape

(4, 6)

In [42]:
medidas_df.axes

[Index(['Ag', 'Au', 'Cu', 'Pt'], dtype='object'),
 Index(['2020', '2021', '2022', '2023', '2024', '2025'], dtype='object')]